### ISSUE TITLE
Section slugs

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen-website#32]
#### Description
Right now section slugs also determine their ordering, this means we need the slug to be something like `1-recipes`.  Ideally the slug could just be `recipes` while setting rank another way.

This decoupling has practical purposes as well, for instance this would prevent dead links if we change orders or add other sections in between existing sections.

I'm not sure if there's a solution here, but wanted to flag it.

**Comment by piotrfonte** [comment]
Fixed, docs sections’ slugs will no longer include order numbers.

**Comment by slifty** [comment]
Hmm -- I'm still seeing them but wondering if maybe I am doing it wrong.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/208884/93922207-9ff8a300-fcdf-11ea-95d9-b9440d14f4e1.png">

**Comment by piotrfonte** [comment]
They seem ok even on the live site:
https://tv.kitchen/docs/recipes/a-recipe-copy

**Comment by slifty** [comment]
I think I'm just misunderstanding what I'm supposed to do to set order.

I had added the numbers in the filenames themselves, so of course slug is confused.

I'm going to see if rank works for order again (it hadn't in the past, but maybe that's fixed!)

**Comment by piotrfonte** [comment]
If I understand correctly what you’re trying to achieve: you should
probably rename your docs folders to get rid of numeral prefixes *and* add
numbers (if needed) to sections names in the frontmatter individually for
all docs from the same section.

**Comment by slifty** [comment]
Got it!  This isn't just for the sections; I would like to be able to rank order the documentation pages themselves.  I'm going to merge in the first round of documentation which should make this easier to diagnose; but also I'll break out of this particular issue since this issue was related to slugs, not order (my mistake!)

**Comment by piotrfonte** [comment]
I can confirm that ordering docs’ pages by rank doesn’t work. Let me look into it.
